"""
Locality Sensitive Hashing on GPUs
"""
from __future__ import annotations
import typing
__all__: list[str] = ['Candidates', 'MinHashCore', 'MinHashIndex', 'RPLSHCore', 'RPLSHIndex']
class Candidates:
    def empty(self) -> bool:
        ...
    def get_counts(self, as_cupy: bool = False) -> typing.Any:
        ...
    def get_indices(self, as_cupy: bool = False) -> typing.Any:
        ...
    def get_offsets(self, as_cupy: bool = False) -> typing.Any:
        ...
    @property
    def n_queries(self) -> int:
        ...
    @property
    def n_total_candidates(self) -> int:
        ...
class MinHashCore:
    def __init__(self, n_hash_tables: typing.SupportsInt, n_hashes: typing.SupportsInt, seed: typing.SupportsInt = 42) -> None:
        ...
    def fit(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.SupportsInt, arg3: typing.SupportsInt) -> MinHashIndex:
        ...
    def fit_query(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.SupportsInt, arg3: typing.SupportsInt) -> Candidates:
        ...
    def query(self, indices: typing.Any, indptr: typing.Any, n_queries: typing.SupportsInt, index: MinHashIndex) -> Candidates:
        ...
    @property
    def n_hash_tables(self) -> int:
        ...
    @property
    def n_hashes(self) -> int:
        ...
    @property
    def seed(self) -> int:
        ...
class MinHashIndex:
    def empty(self) -> bool:
        ...
    def size_bytes(self) -> int:
        ...
    @property
    def n_features(self) -> int:
        ...
    @property
    def n_hash_tables(self) -> int:
        ...
    @property
    def n_hashes(self) -> int:
        ...
    @property
    def n_total_buckets(self) -> int:
        ...
    @property
    def n_total_candidates(self) -> int:
        ...
    @property
    def seed(self) -> int:
        ...
    @property
    def sig_nbytes(self) -> int:
        ...
class RPLSHCore:
    def __init__(self, n_hash_tables: typing.SupportsInt, n_hashes: typing.SupportsInt, seed: typing.SupportsInt = 42) -> None:
        ...
    def fit_double(self, arg0: typing.Any, arg1: typing.SupportsInt, arg2: typing.SupportsInt) -> RPLSHIndex:
        ...
    def fit_float(self, arg0: typing.Any, arg1: typing.SupportsInt, arg2: typing.SupportsInt) -> RPLSHIndex:
        ...
    def fit_query_double(self, arg0: typing.Any, arg1: typing.SupportsInt, arg2: typing.SupportsInt) -> Candidates:
        ...
    def fit_query_float(self, arg0: typing.Any, arg1: typing.SupportsInt, arg2: typing.SupportsInt) -> Candidates:
        ...
    def query_double(self, Q: typing.Any, n_queries: typing.SupportsInt, index: RPLSHIndex, batch_size: typing.SupportsInt | None = None) -> Candidates:
        ...
    def query_float(self, Q: typing.Any, n_queries: typing.SupportsInt, index: RPLSHIndex, batch_size: typing.SupportsInt | None = None) -> Candidates:
        ...
    @property
    def n_hash_tables(self) -> int:
        ...
    @property
    def n_hashes(self) -> int:
        ...
    @property
    def seed(self) -> int:
        ...
class RPLSHIndex:
    def empty(self) -> bool:
        ...
    def size_bytes(self) -> int:
        ...
    @property
    def is_double(self) -> bool:
        ...
    @property
    def n_features(self) -> int:
        ...
    @property
    def n_hash_tables(self) -> int:
        ...
    @property
    def n_hashes(self) -> int:
        ...
    @property
    def n_total_buckets(self) -> int:
        ...
    @property
    def n_total_candidates(self) -> int:
        ...
    @property
    def seed(self) -> int:
        ...
    @property
    def sig_nbytes(self) -> int:
        ...
